import { RestApi } from '@servicenow/sdk/core';
import {
    getReviewRecords,
    getReviewRecordDetail,
    updateReviewRecord,
    getModificationRequests,
    createModificationRequest,
    getKPIs,
    getSourceHealth,
    getSourceExclusions,
    getActiveConnectors,
    getArticleList,
    getModificationStats,
    getReviewerStats,
    getFreshnessStats,
} from '../server/apiHandlers.js';
import { syncConnectors, syncExternalDocs, getConnectorHost, syncKBArticles } from '../server/syncHandlers.js';

/**
 * Knowledge Trust Manager REST API
 * Base URI: /api/x_snc_knowledge_tr/v1/ktm/...
 */
RestApi({
    $id: Now.ID['ktm_rest_api'],
    name: 'Knowledge Trust Manager API',
    serviceId: 'ktm',
    active: true,
    shortDescription: 'API for the Knowledge Trust Manager workspace — provides review records, modification requests, analytics, and configuration data.',
    consumes: 'application/json',
    produces: 'application/json',
    enforceAcl: [],
    versions: [
        {
            $id: Now.ID['ktm_api_v1'],
            version: 1,
            isDefault: true,
            active: true,
            shortDescription: 'Version 1 of the KTM API',
        },
    ],
    routes: [
        // --- Review Records ---
        {
            $id: Now.ID['route_get_reviews'],
            name: 'Get Review Records',
            path: '/review-records',
            method: 'GET',
            script: getReviewRecords,
            version: 1,
            shortDescription: 'Fetch paginated, filterable list of knowledge review records.',
            parameters: [
                { $id: Now.ID['p_status'], name: 'status' },
                { $id: Now.ID['p_freshness'], name: 'freshness' },
                { $id: Now.ID['p_source'], name: 'source' },
                { $id: Now.ID['p_reviewer'], name: 'reviewer' },
                { $id: Now.ID['p_page'], name: 'page' },
                { $id: Now.ID['p_limit'], name: 'limit' },
            ],
        },
        {
            $id: Now.ID['route_get_review_detail'],
            name: 'Get Review Record Detail',
            path: '/review-records/{id}',
            method: 'GET',
            script: getReviewRecordDetail,
            version: 1,
            shortDescription: 'Fetch a single review record with full article content and metadata.',
        },
        {
            $id: Now.ID['route_update_review'],
            name: 'Update Review Record',
            path: '/review-records/{id}',
            method: 'PATCH',
            script: updateReviewRecord,
            version: 1,
            shortDescription: 'Update review status, assign reviewer, add notes, or approve an article.',
        },
        // --- Modification Requests ---
        {
            $id: Now.ID['route_get_mods'],
            name: 'Get Modification Requests',
            path: '/modification-requests',
            method: 'GET',
            script: getModificationRequests,
            version: 1,
            shortDescription: 'Fetch paginated list of modification requests with filters.',
            parameters: [
                { $id: Now.ID['p_mod_state'], name: 'state' },
                { $id: Now.ID['p_mod_assigned'], name: 'assigned_to' },
                { $id: Now.ID['p_mod_priority'], name: 'priority' },
                { $id: Now.ID['p_mod_page'], name: 'page' },
                { $id: Now.ID['p_mod_limit'], name: 'limit' },
            ],
        },
        {
            $id: Now.ID['route_create_mod'],
            name: 'Create Modification Request',
            path: '/modification-requests',
            method: 'POST',
            script: createModificationRequest,
            version: 1,
            shortDescription: 'Create a new modification request linked to a review record.',
        },
        // --- Analytics ---
        {
            $id: Now.ID['route_kpis'],
            name: 'Get KPIs',
            path: '/analytics/kpis',
            method: 'GET',
            script: getKPIs,
            version: 1,
            shortDescription: 'Get summary KPI data: total articles, approval rate, stale rate, open modification requests.',
        },
        {
            $id: Now.ID['route_source_health'],
            name: 'Get Source Health',
            path: '/analytics/source-health',
            method: 'GET',
            script: getSourceHealth,
            version: 1,
            shortDescription: 'Per-connector health scorecard with approval rates and stale percentages.',
        },
        {
            $id: Now.ID['route_mod_stats'],
            name: 'Get Modification Stats',
            path: '/analytics/modification-stats',
            method: 'GET',
            script: getModificationStats,
            version: 1,
            shortDescription: 'Modification request analytics: by state, by type, avg resolution time.',
        },
        {
            $id: Now.ID['route_reviewer_stats'],
            name: 'Get Reviewer Stats',
            path: '/analytics/reviewer-stats',
            method: 'GET',
            script: getReviewerStats,
            version: 1,
            shortDescription: 'Reviewer performance: articles assigned, top reviewers, unassigned count.',
        },
        {
            $id: Now.ID['route_freshness_stats'],
            name: 'Get Freshness Stats',
            path: '/analytics/freshness-stats',
            method: 'GET',
            script: getFreshnessStats,
            version: 1,
            shortDescription: 'Freshness distribution, age buckets, coverage gaps, mod requests per source.',
        },
        // --- Configuration ---
        {
            $id: Now.ID['route_get_exclusions'],
            name: 'Get Source Exclusions',
            path: '/source-exclusions',
            method: 'GET',
            script: getSourceExclusions,
            version: 1,
            shortDescription: 'Fetch all source exclusion configuration records.',
        },
        // --- Connectors ---
        {
            $id: Now.ID['route_get_connectors'],
            name: 'Get Active Connectors',
            path: '/connectors',
            method: 'GET',
            script: getActiveConnectors,
            version: 1,
            shortDescription: 'Get distinct active source connector names and types for filter pills.',
        },
        // --- Article List ---
        {
            $id: Now.ID['route_get_article_list'],
            name: 'Get Article List',
            path: '/article-list',
            method: 'GET',
            script: getArticleList,
            version: 1,
            shortDescription: 'Fetch paginated list of synced articles with title and URL.',
            parameters: [
                { $id: Now.ID['p_al_source'], name: 'source' },
                { $id: Now.ID['p_al_source_type'], name: 'source_type' },
                { $id: Now.ID['p_al_page'], name: 'page' },
                { $id: Now.ID['p_al_limit'], name: 'limit' },
            ],
        },
        // --- Sync ---
        {
            $id: Now.ID['route_sync_connectors'],
            name: 'Sync External Connectors',
            path: '/sync-connectors',
            method: 'POST',
            script: syncConnectors,
            version: 1,
            shortDescription: 'Scan published kb_knowledge articles and create review records.',
        },
        {
            $id: Now.ID['route_sync_kb_articles'],
            name: 'Sync KB Articles',
            path: '/sync-kb-articles',
            method: 'POST',
            script: syncKBArticles,
            version: 1,
            shortDescription: 'Scan all published ServiceNow KB articles and create review records + article list entries.',
        },
        {
            $id: Now.ID['route_sync_ext_docs'],
            name: 'Sync External Documents',
            path: '/sync-external-docs',
            method: 'POST',
            script: syncExternalDocs,
            version: 1,
            shortDescription: 'Create review records from external documents (AI Search results).',
        },
        {
            $id: Now.ID['route_resolve_urls'],
            name: 'Get Connector Host',
            path: '/connector-host',
            method: 'GET',
            script: getConnectorHost,
            version: 1,
            shortDescription: 'Returns the base host URL for an external content connector.',
        },
    ],
});
